apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myprojects
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mosceo/argocd.git
    targetRevision: HEAD
    path: resources
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
